Boilerplate
talkabit/talkabit pull request #29
Opened 2020-10-17 18:12 UTC by pedromsfernandes

# Description

Simple Gatsby boilerplate to kickstart the development of the 2021 website.

# Tasks

- [x] Add Gatsby starter
- [x] Add JSON, Markdown and image plugins
- [x] Add sample JSON query

2020-10-17 18:14 UTC, EstevesAndre commented
Que máquina
Fizeste tudo !

2020-10-17 18:14 UTC, EstevesAndre submitted a review, later dismissed

2020-10-17 22:37 UTC, CiscoFrisco submitted a review, later dismissed

2020-10-18 09:05 UTC, imnotteixeira requested changes

2020-10-18 09:05 UTC, imnotteixeira commented on package.json
> +  }
I think we should be using eslint. It does actual linting (not only formatting), which might be more helpful in catching bugs (e.g. it catches unused vars, re-assignments when they should not occur, specific react stuff, etc..)

The second thing is that this (husky) is not as good as it seems. Sometimes we just want to commit something fast, in order not to lose work (in our separate branch, so no problem) and this would prevent that. And you can have a lot of tiny rules that require some time to fix when you are developing in react (i.e props must be in PropTypes)

I think the best option is to put this check in a circle-ci/travis/github actions pipeline and remove it from here

2020-10-18 10:27 UTC, pedromsfernandes commented on package.json
> +  }
Do you have any suggestions for the eslint configuration? I was thinking of extending airbnb's config.

2020-10-18 10:36 UTC, imnotteixeira commented on package.json
> +  }
https://github.com/NIAEFEUP/nijobs-fe/blob/develop/.eslintrc 

This one. It's been iterated multiple times to match our needs in a react project, so it should be ok. It also has linting of react hooks which is really handy

2020-10-18 11:09 UTC, imnotteixeira approved these changes

2020-10-18 14:00 UTC, CiscoFrisco approved these changes

2020-10-18 16:39 UTC, EstevesAndre approved these changes

2020-10-18 16:51 UTC, merged