Activity template
talkabit/talkabit pull request #30
Opened 2020-10-24 17:18 UTC by pedromsfernandes

# Description

Added Activity template page, that could be used for talks, workshops and panels. I used some of the events from last year to make the mock data, that is being fetched by Gatsby to generate the activity standalone pages. I didn't add them to the index page (that's part of another issue), so here's a list of pages:

- `/talk/graphics-technology-evolution-during-the-current-generation-of-consoles/`
- `/panel/how-society-is-being-shaped-by-technology/`
- `/workshop/how-to-build-a-multiplatform-desktop-app-using-web-technologies/`
- `/talk/the-challenges-of-software-engineering-in-f1/`
- `/talk/the-past-present-and-future-of-privacy/`

If you're running the `develop` script locally, you can also access a random page, such as `/asdasd`, and you'll see a list of available pages.

# Tasks

- [x] Add mock data for events
- [x] Create activity template
- [x] Automatically create pages for each event

2020-10-24 17:57 UTC, imnotteixeira requested changes

2020-10-24 17:57 UTC, imnotteixeira commented on src/components/activity/speaker.js
> +    speaker: { name, occupations, bio, role, img, linkedin },
You should pass the props individually (e.g. a prop for name, another for bio etc) as this is a component for a single speaker, so it does not make sense to wrap in an object. Also, in terms of good practices, it's better that way since the refferences to other props won't change and you get better performance on selective updates/re-renders. (this is probably not the case with this component, but just giving by 2 cents here)

2020-10-24 17:57 UTC, imnotteixeira commented on src/templates/activity.js
> +                    <Speaker key={speaker.name} speaker={speaker} />
regarding the suggestion about the props, you can have `<Speaker key={speaker.name} {...speaker} />` and you won't need to specify each speaker prop individually.

2020-10-24 17:57 UTC, imnotteixeira commented on src/templates/activity.js
> +                    <Speaker key={speaker.name} speaker={speaker} />
If there are two speakers with the samen name (rare, but possible) this will cause problems. Let's use a different key, which we'll know for sure that it is unique, such as the linkedin link (if we ensure there's always one, or a hash of the bio

2020-10-24 17:57 UTC, imnotteixeira commented on src/templates/activity.js
> +const Activity = ({ data }) => {
Same suggestion on the prop separation, make this receive the props you actually want (
`       title,
        type,
        date,
        startTime,
        endTime,
        speakers,`
) and have a wrapper that parses the data and renders an Activity with the required fields:

```
const Activity = ({
        title,
        type,
        date,
        startTime,
        endTime,
        speakers,
    }) => {
......
}

const TemplateWrapper = ({data}) => {
const activityProps = data.markdownRemark.frontmatter;
  return (
    <Activity
         {...activityProps}
     />
  )
}

export default TemplateWrapper;
```
You can later make the TemplateWrapper more generic for other templates and pass a component to be rendered as a prop, instead of always rendering an `Activity`

2020-10-24 17:57 UTC, imnotteixeira commented on src/templates/activity.js
> +                {endTime}
Use a template string
```
<div>{`${startTime} - ${endTime}`}</div>
```

It will also fix the missing space after the '-'

2020-10-24 17:57 UTC, imnotteixeira commented on src/templates/activity.js
> +                speakers: PropTypes.arrayOf(PropTypes.shape({})),
You can use PropTypes.object, instead of PropTypes.shape({}), however, I would create a Speaker shape definition as an util that can is used in other propTypes definition (such as a speaker component) and import here and in the speaker component, so that the speaker object shape is consistent between uses.

2020-10-25 11:29 UTC, pedrogneto approved these changes

2020-10-28 11:07 UTC, imnotteixeira approved these changes

2020-10-28 11:55 UTC, EstevesAndre approved these changes

2020-10-28 12:02 UTC, merged