Sponsor component
talkabit/talkabit pull request #31
Opened 2020-10-28 00:54 UTC by EstevesAndre

# Description
Added Sponsors and Sponsor components to be seen in Home page (index.js).
It fetchs all the existing sponsors (md files) and groups them by tier to be displayed in that order.
I added the component to the index page to preview the component with the mock data.

![image](https://user-images.githubusercontent.com/22922971/97377485-0e6cea00-18b8-11eb-9230-e9a015c3778f.png)

# Tasks
 
- [x] Create placeholder image(s)
- [x] Create json/md files for each sponsor with name and tier
- [x] Fetch sponsors from files and display them

2020-10-28 11:11 UTC, imnotteixeira requested changes

2020-10-28 11:11 UTC, imnotteixeira commented on src/data/sponsors/test-gold-2.md
> +---
Do we need to have a file for each sponsor? Can't we just have a file with sponsors divided by tiers and each tier would have an array of objects (one for each sponsor)?

2020-10-28 11:20 UTC, pedromsfernandes requested changes
Don't forget to run `npm run lint-fix` before opening a PR!

2020-10-28 11:20 UTC, pedromsfernandes commented on src/components/sponsor/sponsors.js
> +  const groupedData = data.allMarkdownRemark.edges.reduce((storage, item) => {
This is actually not needed: GraphQL provides a `group` attribute that accomplishes exactly this. So the query would be something like:

```graphql
query {
  allMarkdownRemark(filter: {fileAbsolutePath: {regex: "/sponsors/"}}) {
    group(field: frontmatter___tier) {
      edges {
        node {
          frontmatter {
            name
            img {
              childImageSharp {
                id
              }
            }
            tier
          }
        }
      }
    }
  }
}
```

2020-10-28 11:20 UTC, pedromsfernandes commented on src/components/sponsor/sponsors.js
> +      {groupedData.Gold && (
It seems like we are sort of repeating ourselves here, no? If we had a sorted array of the sponsors (first Gold, then Silver, then Bronze), we could just map through it and avoid having 3 consecutive blocks. To do this, I'd suggest making one more change to the query:

```graphql
{
  allMarkdownRemark(filter: {fileAbsolutePath: {regex: "/sponsors/"}}, sort: {order: ASC, fields: frontmatter___tier}) {
    group(field: frontmatter___tier) {
      edges {
        node {
          frontmatter {
            name
            img {
              childImageSharp {
                id
              }
            }
            tier
          }
        }
      }
    }
  }
}
```

This requires that the markdown files have an integer number indicating the order that each tier should have, e.g "0-Gold" or "1-Silver", or another attribute "order".

2020-10-28 11:23 UTC, imnotteixeira commented
> 
> 
> Don't forget to run `npm run lint-fix` before opening a PR!

Adttionally, you can mark this PR as Draft, while it is not ready to go

2020-10-28 12:07 UTC, pedromsfernandes commented on src/components/sponsor/sponsors.js
> +  const groupedData = data.allMarkdownRemark.edges.reduce((storage, item) => {
If we use a single file split into tiers this would no longer be necessary.

2020-10-28 13:03 UTC, EstevesAndre commented on src/components/sponsor/sponsors.js
> +import "./sponsors.css"
Ok, I just removed it and added inline styling to a better testing display.

2020-10-28 14:22 UTC, pedromsfernandes commented on src/data/sponsors.md
> +---
This file isn't needed anymore, right? Other than that, looks good to go!

2020-10-28 15:02 UTC, EstevesAndre commented on src/data/sponsors.md
> +---
Yes, just forget that.
Done!

2020-11-02 12:45 UTC, pedromsfernandes approved these changes

2020-11-02 21:12 UTC, CiscoFrisco approved these changes

2020-11-02 22:49 UTC, merged