activities page
talkabit/talkabit pull request #34
Opened 2020-10-29 19:01 UTC by pedrogneto

### Description
Added the Activities page, created a component for the minimised activity (MinActivity)

### Tasks

- [x] fetch events from markdown files
- [x] create categories (talks, workshops, etc)
- [x] display events in their respective categories, with links for their standalone pages

2020-10-30 19:32 UTC, pedromsfernandes commented on package.json
> +    "lint": "^0.7.0",
What is this doing here? We already have `eslint` for this effect. I also noticed the multiple commits to fix the lint issues. That can be avoided by running `npm run lint-fix` before commiting, and making sure there are no errors.

2020-10-30 19:45 UTC, pedromsfernandes requested changes

2020-10-30 19:45 UTC, pedromsfernandes commented on src/pages/activities.js
> +        <div>
You should be using the existing `<Layout/>` component here, along with the `<SEO/>` component. Right now the title of the page isn't being displayed properly.

2020-10-30 19:45 UTC, pedromsfernandes commented on src/components/minActivity.js
> +                ;
Is this semicolon supposed to be here?

2020-10-30 19:45 UTC, pedromsfernandes commented on src/components/minActivity.js
> +            <Link to={slug}>
You should use a template string to include a forward slash in the beginning of the link. Right now when I click on a link, it takes me to `/activities/talk/etc` instead of `/talk/etc`.

2020-10-30 19:45 UTC, pedromsfernandes commented on src/pages/activities.js
> +        allMarkdownRemark {
There's some problems with this query:

1. We should filter so that we only query files in the `events` folder, so we never get undesired results.
2. In this page there's no need to display the "default" events.
3. We want to display events grouped by category in this page. Instead of doing so in the code, we can change the query, using the `group` attribute, and this returns the events in that structure.

2020-11-03 17:17 UTC, pedromsfernandes requested changes

2020-11-03 17:17 UTC, pedromsfernandes commented on src/components/minActivity.js
> +                ;
Once again, is this semicolon supposed to be here? It's displayed on the website in a weird way:
![image](https://user-images.githubusercontent.com/26689768/98017147-c1789e80-1df6-11eb-8d45-178046288030.png)

2020-11-03 17:17 UTC, pedromsfernandes commented on package-lock.json
> +    "cli-table": {
I don't think you properly uninstalled the `lint` package with `npm un lint`. Anyway, if you didn't install anything new then this file shouldn't be changed.

2020-11-03 17:17 UTC, pedromsfernandes commented on src/pages/activities.js
> +    }
The reason I suggested using the `group` attribute was so that it would be easier to map through the events grouped by category and display them. You're missing one field in the query: `fieldValue`. With this, you know for each array of events, what category they belong to, and don't have to check the frontmatter of each one, like you're doing in line 52.

2020-11-03 17:17 UTC, pedromsfernandes commented on src/pages/activities.js
> +};
Following my previous comment, you don't need to find the categories this way. Additionally, since we're not displaying default events, the `if else` in lines 66-69 is not needed. This is how it could look:

```javascript
{data.allMarkdownRemark.group.map((category) => (
                <div key={category.fieldValue}>
                    <h3>
                        {category.fieldValue}
                    </h3>
                    {category.edges.map((edge) => {
                        const activityProps = { ...edge.node.frontmatter, html: edge.node.html, slug: edge.node.fields.slug };
                        return <MinActivity key={edge.node.frontmatter.title} {...activityProps} />;
                    })}
                </div>
            ))}
```

2020-11-04 18:36 UTC, pedromsfernandes approved these changes

2020-11-04 18:57 UTC, CiscoFrisco approved these changes

2020-11-04 19:00 UTC, EstevesAndre approved these changes

2020-11-05 13:39 UTC, merged