Add Schedule component
talkabit/talkabit pull request #35
Opened 2020-11-04 20:40 UTC by pedromsfernandes

# Description

Added Schedule component to the homepage that displays events from both days in chronological order. We can later tweak what information is displayed for each event depending on the mock-ups.

# Tasks

- [x] Display events in chronological order
- [x] Link events to standalone page

2020-11-05 17:38 UTC, CiscoFrisco commented on src/components/schedule/Event.js
> +    speakers: PropTypes.arrayOf(
Why not use the SpeakerShape defined in the utils/props.js file. Is it because it has some unwanted fields for this case in particular (like bio, linked in and role)?

2020-11-05 17:41 UTC, imnotteixeira commented on src/components/schedule/Event.js
> +    speakers: PropTypes.arrayOf(
If that is the reason you can still use them like PropTypes.shape({name: SpeakerShape.name, ...}) using only the wanted fields

2020-11-05 17:44 UTC, imnotteixeira requested changes

2020-11-05 17:44 UTC, imnotteixeira commented on src/components/schedule/Event.js
> +                ))}
You can replace this with `speakers.map(s => s.name).join(", ")` and avoid the span inside the paragraph

2020-11-05 17:48 UTC, pedromsfernandes commented on src/components/schedule/Event.js
> +                ))}
Can't believe I hadn't thought of that, thanks

2020-11-05 22:32 UTC, CiscoFrisco approved these changes

2020-11-05 23:47 UTC, EstevesAndre approved these changes

2020-11-14 16:58 UTC, pedrogneto approved these changes

2020-11-16 12:35 UTC, imnotteixeira approved these changes

2020-11-16 12:36 UTC, merged